import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createCommandRunner } from './exec.js';
import { createFileWriter } from './fs.js';
import { applyFixDiff, enumerateFixDiffPaths } from './apply-fix-diff.js';
import type { ApplyFixDiffRequest } from './apply-fix-diff.js';

const execFileAsync = promisify(execFile);

const INTEGRATION_TIMEOUT = 30_000;

const UNICODE_PATH = 'héllo wörld.js';

/**
 * Probe repo whose diffs are generated by real git, so the tests exercise the
 * exact output forms `git apply --numstat -z` / `--summary` emit for each
 * diff class (quoting, renames, binary, mode-only).
 */
interface ProbeRepo {
  repoPath: string;
  patches: {
    modification: string;
    renameIntoSubdir: string;
    binary: string;
    modeOnly: string;
    quotedUnicode: string;
  };
  cleanup(): Promise<void>;
}

const createProbeRepo = async (): Promise<ProbeRepo> => {
  const repoPath = await mkdtemp(join(tmpdir(), 'amends-diff-probe-'));
  const git = async (...args: string[]): Promise<string> => {
    const { stdout } = await execFileAsync('git', args, { cwd: repoPath });
    return stdout;
  };

  await git('init', '--initial-branch=main');
  await git('config', 'user.name', 'Amends Test');
  await git('config', 'user.email', 'test@amends.invalid');
  await writeFile(join(repoPath, 'safe.js'), 'const value = 1;\n');
  await writeFile(join(repoPath, 'script.sh'), '#!/bin/sh\necho hi\n');
  await writeFile(join(repoPath, 'bin.dat'), Buffer.from([0, 1, 2, 3]));
  await writeFile(join(repoPath, UNICODE_PATH), 'const x = 1;\n');
  await mkdir(join(repoPath, 'src'), { recursive: true });
  await writeFile(join(repoPath, 'src/deep.js'), 'l1\nl2\nl3\nl4\nl5\nl6\nl7\nl8\n');
  await git('add', '-A');
  await git('commit', '-m', 'probe fixture');

  await writeFile(join(repoPath, 'safe.js'), 'const value = 2;\n');
  const modification = await git('diff');
  await git('checkout', '--', '.');

  await mkdir(join(repoPath, 'src/lib'), { recursive: true });
  await git('mv', 'src/deep.js', 'src/lib/deep.js');
  await writeFile(join(repoPath, 'src/lib/deep.js'), 'l1\nEDITED\nl3\nl4\nl5\nl6\nl7\nl8\n');
  await git('add', '-A');
  const renameIntoSubdir = await git('diff', '--cached', '-M');
  await git('reset', '--hard', 'HEAD');

  await writeFile(join(repoPath, 'bin.dat'), Buffer.from([9, 9, 9, 9]));
  const binary = await git('diff', '--binary');
  await git('checkout', '--', '.');

  await execFileAsync('chmod', ['+x', join(repoPath, 'script.sh')]);
  const modeOnly = await git('diff');
  await execFileAsync('chmod', ['-x', join(repoPath, 'script.sh')]);

  await writeFile(join(repoPath, UNICODE_PATH), 'const x = 2;\n');
  const quotedUnicode = await git('diff');
  await git('checkout', '--', '.');

  return {
    repoPath,
    patches: { modification, renameIntoSubdir, binary, modeOnly, quotedUnicode },
    cleanup: () => rm(repoPath, { recursive: true, force: true }),
  };
};

const BARE_HEADERLESS_DIFF = [
  '--- a/safe.js',
  '+++ b/.github/workflows/evil.yml',
  '@@ -1 +1 @@',
  '-const value = 1;',
  '+evil: true',
  '',
].join('\n');

describe('enumerateFixDiffPaths', () => {
  let repo: ProbeRepo;
  const runner = createCommandRunner();
  const files = createFileWriter();

  beforeAll(async () => {
    repo = await createProbeRepo();
  }, INTEGRATION_TIMEOUT);

  afterAll(async () => {
    await repo.cleanup();
  });

  const requestFor = (fixDiff: string): ApplyFixDiffRequest => ({
    repoPath: repo.repoPath,
    fixDiff,
    env: { PATH: process.env['PATH'] ?? '' },
    timeoutMs: INTEGRATION_TIMEOUT,
  });

  const enumerate = (fixDiff: string) =>
    enumerateFixDiffPaths(requestFor(fixDiff), runner, files);

  it('enumerates the touched path of a plain modification diff', async () => {
    const result = await enumerate(repo.patches.modification);
    expect(result).toEqual({ ok: true, paths: ['safe.js'] });
  });

  it('returns no paths for an empty diff', async () => {
    expect(await enumerate('')).toEqual({ ok: true, paths: [] });
    expect(await enumerate('   \n')).toEqual({ ok: true, paths: [] });
  });

  it('sees through a header-less bare diff to the path git apply will write', async () => {
    const result = await enumerate(BARE_HEADERLESS_DIFF);
    expect(result).toEqual({ ok: true, paths: ['.github/workflows/evil.yml'] });
  });

  it('enumerates a quoted unicode path in its raw unquoted form', async () => {
    const result = await enumerate(repo.patches.quotedUnicode);
    expect(result).toEqual({ ok: true, paths: [UNICODE_PATH] });
  });

  it('enumerates both sides of a rename, including the brace-compacted summary form', async () => {
    const result = await enumerate(repo.patches.renameIntoSubdir);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.paths.sort()).toEqual(['src/deep.js', 'src/lib/deep.js']);
  });

  it('enumerates a binary-file diff', async () => {
    const result = await enumerate(repo.patches.binary);
    expect(result).toEqual({ ok: true, paths: ['bin.dat'] });
  });

  it('enumerates a mode-change-only diff rather than passing it silently', async () => {
    const result = await enumerate(repo.patches.modeOnly);
    expect(result).toEqual({ ok: true, paths: ['script.sh'] });
  });

  it('fails closed on a malformed diff', async () => {
    const result = await enumerate('not a diff at all\njust noise\n');
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.reason).not.toBe('');
  });
});

describe('applyFixDiff', () => {
  it(
    'applies a real modification diff to the worktree',
    async () => {
      const repo = await createProbeRepo();
      try {
        const result = await applyFixDiff(
          {
            repoPath: repo.repoPath,
            fixDiff: repo.patches.modification,
            env: { PATH: process.env['PATH'] ?? '' },
            timeoutMs: INTEGRATION_TIMEOUT,
          },
          createCommandRunner(),
          createFileWriter(),
        );
        expect(result).toEqual({ applied: true });
      } finally {
        await repo.cleanup();
      }
    },
    INTEGRATION_TIMEOUT,
  );

  it(
    'returns a structured failure for a diff that does not apply',
    async () => {
      const repo = await createProbeRepo();
      try {
        const result = await applyFixDiff(
          {
            repoPath: repo.repoPath,
            fixDiff: [
              'diff --git a/missing.js b/missing.js',
              '--- a/missing.js',
              '+++ b/missing.js',
              '@@ -1 +1 @@',
              '-nope',
              '+still nope',
              '',
            ].join('\n'),
            env: { PATH: process.env['PATH'] ?? '' },
            timeoutMs: INTEGRATION_TIMEOUT,
          },
          createCommandRunner(),
          createFileWriter(),
        );
        expect(result.applied).toBe(false);
        if (result.applied) return;
        expect(result.failureSignature).toContain('git apply failed');
      } finally {
        await repo.cleanup();
      }
    },
    INTEGRATION_TIMEOUT,
  );
});
